### PR TITLE
Assignment 1 Submission

### PR DESCRIPTION
**Pull request by Kake27**
changed the file extension to .ipynb

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
No need to add iris it is there in library only so delete it also delete .py file and .ipynb checkpoints. Do these changes

**Comment by Kake27** [comment]
Deleted the .ipynb checkpoints file, .py solution and iris.csv as advised. The iris dataset has been directly imported from the sklearn library. Kindly review the changes.

**Comment by Bhavishya-Gupta** [comment]
> Deleted the .ipynb checkpoints file, .py solution and iris.csv as advised. The iris dataset has been directly imported from the sklearn library. Kindly review the changes.

Checkpoints are still there remove them also rest it is fine

**Comment by Kake27** [comment]
Sorry for my negligence. Checkpoints have been deleted.

**Review by Bhavishya-Gupta — APPROVED** [review]
Submission Accepted

**Pull request merged**
