### PR TITLE
Assignment 2 Aditya Raj NITP (NON-IITK)

### PR DESCRIPTION
**Pull request by hexronuspi**

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Delete your readme file and folder as you are not uploading any dataset and also rename notebook with name and college. Also why are your R2 scores so high like 1 so check there may be an issue and also if not explain how you have achieved that.

**Comment by hexronuspi** [comment]
Done!

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Code is fine now but suggestions for improvement is missing write them also using correlation matrix.

**Comment by hexronuspi** [comment]
Done! Please Check.

**Review by Bhavishya-Gupta — APPROVED** [review]
Submission Accepted

**Pull request merged**
