### PR TITLE
submission for assignment 2

### PR DESCRIPTION
**Pull request by Aditya-Singh0001**
this is the answer for second assignment

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
You have done it well but just one change that you have to create a folder with name and college put both files inside that and submit that. Do these changes then I will accept your submission.

**Comment by Aditya-Singh0001** [comment]
i have added the files n a folder and re uploaded them

**Comment by Bhavishya-Gupta** [comment]
> i have added the files n a folder and re uploaded them

Rename your folder with name and college and delete your previous files lying outside the folder.

**Comment by Aditya-Singh0001** [comment]
I have renamed the folder with name and college and deleted the remaining files

**Comment by Bhavishya-Gupta** [comment]
Actually you have to rename your folder with name and roll no rest all is fine. Sorry for the confusion.

**Comment by Aditya-Singh0001** [comment]
I have renamed the folder

**Comment by Bhavishya-Gupta** [comment]
Also I have figured out that you have written your system path while accessing the excel file this is not done. Basically just write the csv or excel file name if it is in the folder . So make these changes in your notebook also rename with name and roll no and assignment 2.

**Comment by Aditya-Singh0001** [comment]
I have  done the required changes.

**Review by Bhavishya-Gupta — APPROVED** [review]
Great work bro. Keep it up. Submission Accepted

**Pull request merged**
