### PR TITLE
submission of assigment 2 

### PR DESCRIPTION
**Pull request by AritraSarkar1203**
Submission of Assigment 2 as the name of the folder AritraSarkat_VNITNagpur and the folde contain the data set in .xlsx format and the the codes are in .ipynb file .

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Great work but there are few issues firstly why your R2 score is negative for manual linear regression. So correct that and also you have not written suggestions for improvement properly so write that properly. Rest it is looking fine.

**Comment by AritraSarkar1203** [comment]
sir I have made the changes in my repo of the assignment 2 submission
,please check it and it will be helpful if you confirm the submission.

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Delete your previous cell in the notebook where R2 score is negative also still your R2 score is 0.29 it should be in 0.8 so correct that and do that properly. Also do the manual part where it should be done, so shift your last cell up.

**Review by Bhavishya-Gupta — APPROVED** [review]
Submission Accepted

**Pull request merged**
