### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Vanshika-Shankhwar**

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
There are a few issues : 
Create a folder with name and college and put a dataset and notebook inside that. But there is a major issue that your R2 score is negative for manual linear regression. So do these changes

**Comment by Bhavishya-Gupta** [comment]
I can't see your changes it is still the same. Check once again and do the changes properly.

**Comment by Vanshika-Shankhwar** [comment]
> I can't see your changes it is still the same. Check once again and do the changes properly.

Now I've uploaded once again. I hope now there is no error

**Comment by Bhavishya-Gupta** [comment]
You have to use the GitHub desktop or commands as folder uploading is required, do in that way then only you can upload the folder. You are doing it the wrong way. If any doubt is still there ask on WhatsApp dm.

**Comment by Vanshika-Shankhwar** [comment]
> You have to use the GitHub desktop or commands as folder uploading is required, do in that way then only you can upload the folder. You are doing it the wrong way. If any doubt is still there ask on WhatsApp dm.

I have now uploaded the folder.

**Comment by Bhavishya-Gupta** [comment]
Your R2 value for manual is very low just  0.08 that's very low increase it

**Comment by Vanshika-Shankhwar** [comment]
> Your R2 value for manual is very low just 0.08 that's very low increase it

Ok

**Pull request closed without merging**
