### PR TITLE
reuploading after running the code and uplaoding the folder in the correct directory

### PR DESCRIPTION
**Pull request by tusharj23**

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Your R2 score for manual is 0.42 which is very low improvement it should be around 0.8. also suggestions for improvement can be better do these changes also

**Comment by tusharj23** [comment]
> Your R2 score for manual is 0.42 which is very low improvement it should be around 0.8. also suggestions for improvement can be better do these changes also

I have tried a lot but i am getting negative r2 value or around 0.42

**Comment by Bhavishya-Gupta** [comment]
> > Your R2 score for manual is 0.42 which is very low improvement it should be around 0.8. also suggestions for improvement can be better do these changes also
> 
> I have tried a lot but i am getting negative r2 value or around 0.42 

Ok then 0.42 I can accept

**Review by Bhavishya-Gupta — APPROVED** [review]
Submission Accepted. But try to achieve more than 0.42 as it is quite low

**Pull request merged**
