### PR TITLE
Suhani Singh_IIT BHU

### PR DESCRIPTION
**Pull request by SuhaniSingh10**

### CODE REVIEW

**Review by Bhavishya-Gupta — COMMENTED** [review]
Great job. You have done it very nicely just one thing add your csv file and jupyter notebook in the folder and name it as name_college and submit it.

**Comment by SuhaniSingh10** [comment]
> Great job. You have done it very nicely just one thing add your csv file and jupyter notebook in the folder and name it as name_college and submit it. Do these changes.Then I will accept your submission

I have made changes. Thankyou

**Comment by Bhavishya-Gupta** [comment]
> > Great job. You have done it very nicely just one thing add your csv file and jupyter notebook in the folder and name it as name_college and submit it. Do these changes.Then I will accept your submission
> 
> I have made changes. Thankyou

I am not seeing that please check once again I can't see any folder.

**Comment by SuhaniSingh10** [comment]
> > > Great job. You have done it very nicely just one thing add your csv file and jupyter notebook in the folder and name it as name_college and submit it. Do these changes.Then I will accept your submission
> > 
> > 
> > I have made changes. Thankyou
> 
> I am not seeing that please check once again I can't see any folder.

I am doing it now but I can not upload files. my submission will not be considered?

**Comment by Bhavishya-Gupta** [comment]
I will accept it just do what I have asked

**Comment by SuhaniSingh10** [comment]
> I will accept it just do what I have asked. You have submitted before time so these are the issues which obviously will resolve after deadline. So don't worry about accepting I will accept it just do the changes by today night

I have done it now. please check and confirm.

**Comment by Bhavishya-Gupta** [comment]
> > I will accept it just do what I have asked. You have submitted before time so these are the issues which obviously will resolve after deadline. So don't worry about accepting I will accept it just do the changes by today night
> 
> I have done it now. please check and confirm 
Your folder is fine but also delete your previous files which are lying outside the folder

**Review by Bhavishya-Gupta — APPROVED** [review]
Submission Accepted

**Pull request merged**
