### PR TITLE
Assignment 2 PRATEEKPATEL_IITBHU

### PR DESCRIPTION
**Pull request by Prateek-Patel-IITBHU**

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Your notebook is fine but delete other two files which are almost empty also make a folder and move your notebook and dataset in that and submit that.

**Comment by Prateek-Patel-IITBHU** [comment]
> Your notebook is fine but delete other two files which are almost empty also make a folder and move your notebook and dataset in that and submit that.

Done now

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
There are still issues like you have not mentioned scratch model R2 score properly also you have not calculated R2 score using Sklearn and also mention all models performance properly so that I can see that clearly. Do these changes rest it is looking fine

**Review by Bhavishya-Gupta — APPROVED** [review]
Submission Accepted

**Pull request merged**
