### PR TITLE
assignment 2

### PR DESCRIPTION
**Pull request by sarthakshukla19**

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Do your submission again you have uploaded the zip file upload the folder in which there should be a dataset and notebook and name your folder in the specified format. Do these changes then only I will accept your submission

**Review by Bhavishya-Gupta — COMMENTED** [review]
Your submission is fine but I would like to tell you that you have copied from someone else. Don't do it please as it is quite clearly visible. I am seeing all the assignments. I can easily catch it. This is not acceptable. You should not have done this. I want an explanation for it then only I will accept it

**Comment by sarthakshukla19** [comment]
Hello sir,
  I apologize for the copying act. I was involved in other project
assignment (mccabe thele) , so i didn't get time for studying the content,
that's why I copied the assignment. I assure you it won't happen next time.
Sarthak Shukla

**Comment by Bhavishya-Gupta** [comment]
If you need more time dm me I will give you more time. So do it by yourself and submit by tomorrow. I will accept that not the copied one.

**Pull request closed without merging**
