### PR TITLE
Assignment2_231086

### PR DESCRIPTION
**Pull request by tanyasingh0909**
There is some error appear in uploading folder containing csv file, thats why I'm uploading only assignment file here.

### CODE REVIEW

**Comment by Bhavishya-Gupta** [comment]
What error ?  use the GitHub desktop upload folder in which there is a csv file and notebook

**Comment by tanyasingh0909** [comment]
I tried 2-3 times more, but after pushing , my folder still not visible in the forked repository.

**Comment by tanyasingh0909** [comment]
After pushing, Terminal is showing message that "Everything up-to-date", But I don't know my folder is not  visible in the repository.

**Comment by Bhavishya-Gupta** [comment]
Try watching a video or something you will submit it by tomorrow

**Pull request closed without merging**
