### PR TITLE
Shagun_IITBHU

### PR DESCRIPTION
**Pull request by OrganicBeetle**
Hi Maintainers,

Extremely sorry for the delay in submission since i was in transit and thus didnot have access to my laptop. 

I have completed the Assignment and uploaded all the necessary files.
Please let me know in case there is any additional requirement or issues with my PR.

Have a great day!

### CODE REVIEW

**Comment by Bhavishya-Gupta** [comment]
> Hi Maintainers,
> 
> Extremely sorry for the delay in submission since i was in transit and thus didnot have access to my laptop. 
> 
> I have completed the Assignment and uploaded all the necessary files.
> Please let me know in case there is any additional requirement or issues with my PR.
> 
> Have a great day

**Review by Bhavishya-Gupta — COMMENTED** [review]
Your code is fine but it is looking like you have copied it from somebody else. That I can't accept it you need more time I can give but copying I won't accept. So explain to me the reason or I would say by tomorrow so by yourself and submit.

**Comment by OrganicBeetle** [comment]
> Your code is fine but it is looking like you have copied it from somebody else. That I can't accept it you need more time I can give but copying I won't accept. So explain to me the reason or I would say by tomorrow so by yourself and submit.

Extremely Sorry about this, I was unsure about how to answer the final Question 5 and thus had copied it from a friend after he explained it to me. 
The rest of the code is completely written by me and assure you i thoroughly understand my code although i did take some help from ChatGPT, and had looked at a few solutions to see the contents of their notebook like the Feature Importance which I added after I saw one solution utilize it, and another implementation of the manual linear regression which i found really nice and thus implemented it.

Extremely Sorry about this, I assure you this will not be repeated in the future and I can redo the entire submission and submit it today if needed.

Thank you for your time and consideration.

**Comment by Bhavishya-Gupta** [comment]
If you can please redo it by yourself. Baaki if you want I can excuse this time and submit this submission also. Tell me what you want. But don't copy from next time.

**Comment by OrganicBeetle** [comment]
Thank you for your understanding and consideration. I would be grateful if you could accept my current submission, as I believe only a few parts of the code would be different.

I assure you that I have learned from this mistake, and it will not be repeated in the future. I sincerely hope you can excuse me this once.

**Comment by Bhavishya-Gupta** [comment]
> Thank you for your understanding and consideration. I would be grateful if you could accept my current submission, as I believe only a few parts of the code would be different.
> 
> I assure you that I have learned from this mistake, and it will not be repeated in the future. I sincerely hope you can excuse me this once.

Ok I am excusing you for this time

**Comment by Bhavishya-Gupta** [comment]
Rename the folder name with name and college no need to add assignment

**Comment by Bhavishya-Gupta** [comment]
I asked for folder name not file name.

**Pull request closed without merging**
