### PR TITLE
Nancy Babel_IIT(BHU)

### PR DESCRIPTION
**Pull request by nancybabel**

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Just add your excel file with a notebook in the folder and submit that. Then I wil accept your submission. Btw you have done it very nicely. Amazing work

**Comment by nancybabel** [comment]
> Just add your excel file with a notebook in the folder and submit that. Then I will accept your submission. Btw you have done it very nicely. Amazing work

Done. Thank you

**Comment by Bhavishya-Gupta** [comment]
> > Just add your excel file with a notebook in the folder and submit that. Then I will accept your submission. Btw you have done it very nicely. Amazing work
> 
> Done. Thank you

That is fine but I found another issue like why your ridge lasso and Sklearn R2 score values are exactly same check if your loop is running properly or not. I doubt that it is running properly

**Review by Bhavishya-Gupta — APPROVED** [review]
Amazing work. You have done it very nicely. Keep it up. Submission Accepted

**Comment by nancybabel** [comment]
> > > Just add your excel file with a notebook in the folder and submit that. Then I will accept your submission. Btw you have done it very nicely. Amazing work
> > 
> > 
> > Done. Thank you
> 
> That is fine but I found another issue like why your ridge lasso and Sklearn R2 score values are exactly same check if your loop is running properly or not. I doubt that it is running properly

Thanks for mentioning. Fixed it.

**Pull request merged**
