### PR TITLE
Assignment2

### PR DESCRIPTION
**Pull request by Smira888**

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
I can't see any change . The R2 score is still less. So correct it.

**Comment by Smira888** [comment]
How much should the R2 score be and in which model should i improve? Can you please specify a bit about the changes?

**Comment by Smira888** [comment]
I have made the changes please check if anything else is required.

**Review by Bhavishya-Gupta — APPROVED** [review]
Submission Accepted

**Pull request merged**
