### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by brijeshkumar-pj**

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
There are issues to fix them : 
Firstly don't need to make any folder just save your .ipynb file with the specified format. Do that and also in your .ipynb file run it properly as output of cells are not visible so do it resave it and re upload also delete the folder just save it in assignment 1. Do that and then I will accept it. You have submitted quite late as it is many hours after the deadline you have submitted. But still as it is the first time I will be accepting it after you will fix the issues but not from the second assignment.

**Comment by brijeshkumar-pj** [comment]
submitted new file with specified format

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Your .ipynb file is fine but also remove your folder which you have uploaded before which is lying outside assignment 1 folder remove that. Rest it is fine.

**Review by Bhavishya-Gupta — APPROVED** [review]
Submission Accepted

**Pull request merged**
