### PR TITLE
Submitting the second assignment

### PR DESCRIPTION
**Pull request by MayankRaj2348**
This pull Request is made to submit the second assignment of the project

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Your solution is incomplete complete it R2 score for Sklearn is missing. Also suggestions for improvements are missing. It is very incomplete to do it properly then only I will accept the submission.

**Comment by MayankRaj2348** [comment]
The requested changes have been made. The R2 score of sklearn has been added in cell number 25 and suggestions to improve have been added at the last

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
It is still having issues your r2 score for some model is coming negative which should not be also make a folder and move your excel and notebook in that and submit that.

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
Your folder has some issues firstly in your folder there is file name assignment 2 which is of no use delete also you have to add .ipynb file you have added .txt file also rename your folder with name and college

**Comment by Bhavishya-Gupta** [comment]
Bro do it properly upload .ipynb file not .ipynb.txt also rename folder with name and college

**Review by Bhavishya-Gupta — APPROVED** [review]
Submission Accepted

**Pull request merged**
