### PR TITLE
Assignment 2(Parth_iitbombay)

### PR DESCRIPTION
**Pull request by OGCoderOggy**

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
It is incomplete. Complete it properly then submit it. I am giving you time till tomorrow. Do it by then.

**Comment by OGCoderOggy** [comment]
done
sorry for delay.
I was away yesterday.

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
You have done it well just if you can please improve suggestions for improvement you have just written one line try to relate with correlation matrix also your manual R2 score is very less try to increase it. Rest is looking fine. Do these changes then I will accept your submission

**Comment by OGCoderOggy** [comment]
done

**Review by Bhavishya-Gupta — APPROVED** [review]
Submission Accepted. Well tried but try to increase the manual model R2 score so that your model will perform better.

**Pull request merged**
