### PR TITLE
Assignment 2 

### PR DESCRIPTION
**Pull request by SurviKumari2004**

### CODE REVIEW

**Review by Bhavishya-Gupta — CHANGES_REQUESTED** [review]
There are a few issues : 
It's nice that you have added csv file but it will be better if you make a folder name it name and college and put csv and notebook inside it then submit also check that in your notebook manual linear regression R2 score is 0.751 which is quite low try to increase it and then submit it.

**Review by Bhavishya-Gupta — COMMENTED** [review]
Great job. You have done it well. Submission Accepted

**Review by Bhavishya-Gupta — APPROVED** [review]
Great job. You have done it well. Submission Accepted

**Comment by SurviKumari2004** [comment]
Thank you!

**Pull request merged**
